#pragma once

// Window Settings
#define WINDOW_SIZES 500, 600 
#define WINDOW_POSITION SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED
#define WINDOW_FLAGS SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE

// Game Settings
#define GAME_TITLE "Adventure"
 