DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Assets;
DROP TABLE IF EXISTS Texture;
DROP TABLE IF EXISTS Shader;
DROP TABLE IF EXISTS Project;
DROP TABLE IF EXISTS History;
DROP TABLE IF EXISTS Objects;
DROP TABLE IF EXISTS Properties;
DROP TABLE IF EXISTS Transpose;
DROP TABLE IF EXISTS ColorBox;
DROP TABLE IF EXISTS Contributors;
DROP TABLE IF EXISTS EditorGui;
DROP TABLE IF EXISTS ObjectGui;
DROP TABLE IF EXISTS LogGui;

PRAGMA foreign_keys = ON;

CREATE TABLE User (
  nick TEXT PRIMARY KEY,
  password TEXT NOT NULL,
  active TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

----------- [Assets] ----------- 
CREATE TABLE Assets (
  id INTEGER PRIMARY KEY,
  user TEXT NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  FOREIGN KEY (user) REFERENCES User(nick) ON DELETE CASCADE
);

CREATE TABLE Texture (
  asset_id INTEGER PRIMARY KEY,
  width INTEGER NOT NULL DEFAULT 64,
  height INTEGER NOT NULL DEFAULT 64,
  FOREIGN KEY (asset_id) REFERENCES Assets(id) ON DELETE CASCADE
);

CREATE TABLE Shader (
  asset_id INTEGER PRIMARY KEY,
  data TEXT NOT NULL DEFAULT '',
  FOREIGN KEY (asset_id) REFERENCES Assets(id) ON DELETE CASCADE
);

----------- [Project] -----------
CREATE TABLE Project (
  id INTEGER PRIMARY KEY,
  owner_id TEXT NOT NULL,
  name TEXT NOT NULL,
  last_synced TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner_id) REFERENCES User(nick) ON DELETE CASCADE
);

CREATE TABLE Contributors (
  id INTEGER PRIMARY KEY,
  project INTEGER NOT NULL,
  user TEXT NOT NULL,
  joined TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  width INTEGER NOT NULL DEFAULT 800,
  height INTEGER NOT NULL DEFAULT 600,
  FOREIGN KEY (project) REFERENCES Project(id) ON DELETE CASCADE,
  FOREIGN KEY (user) REFERENCES User(nick) ON DELETE CASCADE  
);

CREATE TABLE History (
  id INTEGER PRIMARY KEY,
  project_id INTEGER NOT NULL,
  action TEXT NOT NULL,
  done TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES Project(id) ON DELETE CASCADE
);

CREATE TABLE Objects (
  id INTEGER PRIMARY KEY,
  project INTEGER NOT NULL,
  name TEXT NOT NULL,
  FOREIGN KEY (project) REFERENCES Project(id) ON DELETE CASCADE
);

----------- [Properties] -----------
CREATE TABLE Properties (
  id INTEGER PRIMARY KEY,
  object INTEGER NOT NULL,
  type TEXT NOT NULL,
  FOREIGN KEY (object) REFERENCES Objects(id) ON DELETE CASCADE,
  UNIQUE(object, type)
);

CREATE TABLE Transpose (
  properties_id INTEGER PRIMARY KEY,
  x INTEGER NOT NULL DEFAULT 0,
  y INTEGER NOT NULL DEFAULT 0,
  z INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (properties_id) REFERENCES Properties(id) ON DELETE CASCADE
);

CREATE TABLE ColorBox (
  properties_id INTEGER PRIMARY KEY,
  red INTEGER NOT NULL DEFAULT 0,
  green INTEGER NOT NULL DEFAULT 0,
  blue INTEGER NOT NULL DEFAULT 0,
  alpha INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (properties_id) REFERENCES Properties(id) ON DELETE CASCADE
);

----------- [Editor] -----------
CREATE TABLE EditorGui (
  id INTEGER PRIMARY KEY,
  contributor INTEGER NOT NULL,
  type TEXT NOT NULL,
  FOREIGN KEY (contributor) REFERENCES Contributors(id) ON DELETE CASCADE
);

CREATE TABLE ObjectGui (
  editor_gui_id INTEGER PRIMARY KEY,
  FOREIGN KEY (editor_gui_id) REFERENCES EditorGui(id) ON DELETE CASCADE
);

CREATE TABLE LogGui (
  editor_gui_id INTEGER PRIMARY KEY,
  FOREIGN KEY (editor_gui_id) REFERENCES EditorGui(id) ON DELETE CASCADE
);